sudo: required
services:
- docker

script:
- "./docker_build.sh"
- "./docker_run.sh"

deploy:
  provider: releases
  file: "/build/yellow_paper.pdf"
  skip_cleanup: true
  on:
    branch: testing-travis
