sudo: required

services:
  - docker

cache:
  directories:
  - $HOME/build
  - $HOME/sections/graphviz-images
  - ./sections/graphviz-images
  - ./build
  - $TRAVIS_BUILD_DIR/sections/graphviz-images
  - $TRAVIS_BUILD_DIR/build

script:
  - ./docker_build.sh
  - ./docker_run.sh
