sudo: required
services:
- docker

script:
- ./docker_build.sh
- ./docker_run.sh

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: 
    - ./build/yellow_paper.pdf
  skip_cleanup: true
  on:
    tags: true
