sudo: required

services:
  - docker

script:
  - ./docker_build.sh
  - ./docker_run.sh
  
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "/build/yellow_paper.pdf"
  skip_cleanup: true
  on:
    tags: true  
