sudo: required
services:
- docker
script:
- "./docker_build.sh"
- "./docker_run.sh"
deploy:
  provider: releases
  api_key:
    secure: ./github_deploy_key.enc
  file:
  - "./build/yellow_paper.pdf"
  skip_cleanup: true
  on:
    branch: test-deploy-travis

