version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: build
          command: ./docker_build.sh
      - run:
          name: generatePDFs
          command: ./docker_run.sh
      - run: echo "A first hello"
