version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      # build the application image
      - run: ./docker_build.sh
      - run: ./docker_run.sh
      - run: echo "A first hello"
